### ISSUE TITLE
Message more than 160 issue with Async feature

### ISSUE THREAD

**Issue by poonamkumariasp** [AdhamAwadhi/JamaaSMPP#10]
Hi, 
I am facing issue while i am trying to send a long message using async feature.
I am able to send same long message using sync feature.
Please find the following code for your reference.
Please help. I am stuck.

Thanks,
Poonam

/// <summary>
        /// Sends SMS asynchronously
        /// </summary>
        public void SendSMSAsync()
        {
            TextMessage msg = new TextMessage();
            msg.DestinationAddress = Settings.Default.SampleDestinationAddress;
            msg.SourceAddress = Settings.Default.SampleSourceAddress;
            msg.Text = Settings.Default.SampleMessageLong;
            msg.RegisterDeliveryNotification = Settings.Default.RegisterDeliveryNotification;
            
            SmppClient client = GetSmppClient();
            if (client.ConnectionState != SmppConnectionState.Connected) client.ForceConnect(5000);
            if (client.ConnectionState == SmppConnectionState.Connected)
                client.BeginSendMessage(msg, SendMessageCompleteCallback, client);            
        }

**Comment by AdhamAwadhi** [comment]
Can you tell what is the issue exactly? Did you got any exceptions? Or what?

**Comment by poonamkumariasp** [comment]
Hi Adham, I am getting thread was aborted exception in callback method.

My callback method is below:

  /// <summary>
        /// Callback method
        /// </summary>
        /// <param name="result"></param>
        private void SendMessageCompleteCallback(IAsyncResult result)
        {
            try
            {
                SmppClient client = (SmppClient)result.AsyncState;
            client.EndSendMessage(result);

            }
            catch (Exception e)
            {


            }
        }


Image: 

![image](https://user-images.githubusercontent.com/13271953/35436318-9f305f1c-0296-11e8-9cec-bd5172b0009d.png
![exceptionsmpp](https://user-images.githubusercontent.com/13271953/35436362-c4dccb9c-0296-11e8-80a7-ff47de14cd95.png)

**Comment by poonamkumariasp** [comment]
Please let me know if you need further details on this. Thanks a lot.

**Comment by AdhamAwadhi** [comment]
I tried it, and it's worked. **Can you send me the StackTrace and TargetSite of exception.** 
**I'm not sure** but I think it's Timedout.

**Comment by poonamkumariasp** [comment]
Hi Adham,

Please share the code which is working for you for asynchronous. I am also
having trouble in receiving mesgaes. I will try your code and see if that
works for me.

Thanks,
Poonam

**Comment by AdhamAwadhi** [comment]
Please note **I'm using SMPPSim** for testing. The code is the same from  **[DemoClient](https://github.com/AdhamAwadhi/JamaaSMPP/blob/master/DemoClient/Program.cs)** project. Just changed the `msg.Text`, send with `client.BeginSendMessage(msg, SendMessageCompleteCallback, client);` and used your  `SendMessageCompleteCallback`

**Comment by poonamkumariasp** [comment]
It is working for me now. I think there was some issue in my unit test.
