### ISSUE TITLE
[Typo] TypeOfNumber should be Alphanumeric instead of Aphanumeric

### ISSUE THREAD

**Issue by iSatishYadav** [AdhamAwadhi/JamaaSMPP#19]
**[Typo] TypeOfNumber should be Alphanumeric instead of Aphanumeric**

https://github.com/AdhamAwadhi/JamaaSMPP/blob/90f7b13bf64445221b88dc9ffaf17f69d4eb3749/JamaaTech.SMPP.Net.Lib/TypeOfNumber.cs#L30

`JamaaTech.Smpp.Net.Lib.TypeOfNumber` `enum` has a value (5) named `Aphanumeric`, it's a typo and it should be `Alphanumeric` instead.

**Comment by AdhamAwadhi** [comment]
Thanks @iSatishYadav . Updated source code.
