### ISSUE TITLE
Arabic Messages

### ISSUE THREAD

**Issue by ahmadnegm** [AdhamAwadhi/JamaaSMPP#2]
What are the proper Encoding to get Arabic messages correctly? Because I tried ASCII, SMSCDefault, Latin_Hebrew and UCS2 are not working well, it always appears like "????????".

**Comment by AdhamAwadhi** [comment]
How did you used the Encoding? _Can you give some code._

**Comment by ahmadnegm** [comment]
I used the same Demo project:

```
private static ISmppConfiguration GetSmppConfiguration()
{
	return new SmppConfiguration
	{
		TimeOut = 60000,
		StartAutomatically = true,
		Name = "MyLocalClient",
		SystemID = "xxxx",
		Password = "xxxxxx",
		Host = "10.100.190.40",
		Port = 9000,
		SystemType = "",
		DefaultServiceType = "",
		SourceAddress = "",
		AutoReconnectDelay = 5000,
		KeepAliveInterval = 5000,
		ReconnectInteval = 10000,
		Encoding = JamaaTech.Smpp.Net.Lib.DataCoding.UCS2
	};
}
```
And I changed UCS2 to ASCII and SMSCDefault, but both return Arabic text in incorrect format.

**Comment by AdhamAwadhi** [comment]
After testing on real and demo SMSCs, I found some of them accept `Encoding.BigEndianUnicode` (as in my real SMSC in my country) and others accept `Encoding.UTF8` (as in demo SMSC). So I made new property on `SMPPEncodingUtil` to allow user to set preferred Encoding.

You can use it as below:

        SMPPEncodingUtil.UCS2Encoding = Encoding.BigEndianUnicode;
