### ISSUE TITLE
Acknowledgement needs to go from ESME to the SMSC

### ISSUE THREAD

**Issue by poonamkumariasp** [AdhamAwadhi/JamaaSMPP#21]
Hi Adham,

I have created following acknowledgement which needs to be sent from my ESME to the SMSC.

 **var encSrv = new SmppEncodingService();
 PDUHeader pduheader = new PDUHeader(CommandType.DeliverSmResp, (uint)e.ShortMessage.SequenceNumber, SmppErrorCode.ESME_ROK);
  var pdu = PDU.CreatePDU(pduheader, encSrv);**

Can you please tell me how can I send this pdu from my ESME to the SMSC now.

Thanks,
Poonam

**Comment by AdhamAwadhi** [comment]
Hi @poonamkumariasp I created new method to send pdu. see [SmppClient.cs - L214](https://github.com/AdhamAwadhi/JamaaSMPP/blob/056d59c2ac9740df8352e349eeba1099667e07e0/JamaaTech.Smpp.Net.Client/SmppClient.cs#L214)
