### ISSUE TITLE
SmppErrorCode 1024 ?

### ISSUE THREAD

**Issue by johanosventer** [AdhamAwadhi/JamaaSMPP#22]
Hi,

I'm trying to send an SMS to an international (+44) number (we're in South Africa), according to the logs we're getting a SmppException with an ErrorCode property that reports a 'ToString()' value of 1024.  This is obviously not in the Enum for SmppErrorCode.

Any Ideas?

Regards,

**Comment by AdhamAwadhi** [comment]
You need to ask your provider, Any error code not in the Enum is a custom error from the provider.
