### ISSUE TITLE
Combining UDH Message

### ISSUE THREAD

**Issue by gerann0204** [AdhamAwadhi/JamaaSMPP#23]
Do you have sample code that combine the UDH message/concatenated message in submit_sm.

**Comment by AdhamAwadhi** [comment]
It's already support concatenated if text is long. But you can see [TextMessage.cs - L80](https://github.com/AdhamAwadhi/JamaaSMPP/blob/056d59c2ac9740df8352e349eeba1099667e07e0/JamaaTech.Smpp.Net.Client/TextMessage.cs#L80)
