### ISSUE TITLE
'+' prefix when SMS is received on the mobile phone

### ISSUE THREAD

**Issue by Dmitry163** [AdhamAwadhi/JamaaSMPP#30]
Hi Adham,

the source address that I use which is 2345 appears in international number format with a '+' prefix when SMS is received on the mobile phone i.e as +2345. I want the source address(sender) to appear as 2345 only, without the '+' sign. What should I do?

**Comment by AdhamAwadhi** [comment]
You need to change `AddressNpi` and `AddressTon`. But you should review your provider it's depends on thier configurations.
_In a simple way I just trim the '+' sing before processing._
