### ISSUE TITLE
JamaaTech.Smpp.Net.Lib.Util.SMSCDefaultEncoding Exception

### ISSUE THREAD

**Issue by miloja99** [AdhamAwadhi/JamaaSMPP#4]
Im trying to send sms with my gateway 2N VoiceBlue Next , using default SMSC encoding not working, using any other enconding the message is dispatched but  rejected by the  Celullar Network. Seems like something is wrong in my code. I suspect about enconding but cant use SMSCDefault.
Using 1.5.2 version of your library. 

            SmppClient client = new SmppClient();
          try
            {
                SmppConnectionProperties properties = client.Properties;
                properties.SystemID = systemId;
                properties.Password = password;
                properties.Port = port;
                properties.Host = server;
               properties.AddressNpi = JamaaTech.Smpp.Net.Lib.NumberingPlanIndicator.Unknown;
                properties.AddressTon = JamaaTech.Smpp.Net.Lib.TypeOfNumber.Unknown;
               properties.DefaultEncoding = JamaaTech.Smpp.Net.Lib.DataCoding.SMSCDefault;
               client.AutoReconnectDelay = 3000;
                client.KeepAliveInterval = 15000;
                client.Start();

                if (client.ConnectionState != SmppConnectionState.Connected) client.ForceConnect(5000);

               TextMessage msg = new TextMessage();
                msg.DestinationAddress = recipient;
                msg.Text = text;
                msg.RegisterDeliveryNotification = false;                
                if (client != null)
                {
                    client.SendMessage(msg);    <---------- exception here with SMSCDefault
                    client.Shutdown();
                }

**Comment by AdhamAwadhi** [comment]
Can  you get the whole exception details?

**Comment by zh4r0nax** [comment]
i think DataCoding.ASCII

**Comment by embula** [comment]
I've integrated  but the application throws an exception after sending 3-5 SMS. I'm getting the exception below

   Bind Operation failed. PDU receive operation timed out

Any ideas on how to fix this?
