### ISSUE TITLE
Missing Source address TON setting

### ISSUE THREAD

**Issue by Kirembu** [AdhamAwadhi/JamaaSMPP#5]
Some providers require the Source Address Type of Number Specified.
This is in case you are sending an SMS from an Alphanumeric source address:

I was hopping that this could be included in SmppConnectionProperties

[SmppConnectionProperties](https://github.com/AdhamAwadhi/JamaaSMPP/blob/master/JamaaTech.Smpp.Net.Client/SmppConnectionProperties.cs)

Right now we get an exception from our provider (MTN Swaziland) if we do not specify the Source Address Type of Number for Alphanumeric source addresses.

**Comment by AdhamAwadhi** [comment]
You can set it as :
`client.Properties.AddressTon = JamaaTech.Smpp.Net.Lib.TypeOfNumber.Aphanumeric`

**Comment by AdhamAwadhi** [comment]
**Sorry, I misunderstood you.**
For now you can work around (till I find a time to fix this) by override `TextMessage.GetPDUs` and set the source Ton as 

        SubmitSm sm = new SubmitSm();
        sm.SourceAddress.Ton = TypeOfNumber.Aphanumeric; // or what you want
        // ........

**Comment by AdhamAwadhi** [comment]
I updated the `TextMessage`  by creating virtual method `CreateSubmitSm()` to allow user to change some properties (like Source address ton), look below:

        class MyTextMessage : TextMessage
        {
            protected override SubmitSm CreateSubmitSm()
            {
                var sm = base.CreateSubmitSm();
                sm.SourceAddress.Ton = JamaaTech.Smpp.Net.Lib.TypeOfNumber.Aphanumeric;
                return sm;
            }
        }
