### ISSUE TITLE
Improvements for the error logging

### ISSUE THREAD

**Issue by mdentremont** [AdhamAwadhi/JamaaSMPP#7]
When a bind fails to connect, the isn't much information given by the library. It would be nice if more information about the failure reason could be included in connection state changed event.

**Comment by mdentremont** [comment]
It does look like the `sender` object has a `vLastException` private/protected member - we might be able to hoist this to a public property so clients could then add it to their error logging

**Comment by AdhamAwadhi** [comment]
It's ready. Thank you @mdentremont
