### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by mcknight89** [AdhamAwadhi/JamaaSMPP#9]
It seems like the Nuget package is quite out of date?

Any chance it can be updated to the latest version?

**Comment by AdhamAwadhi** [comment]
I'm working on **dotnet core**, I will publish it (once) as soon as possible

**Comment by AdhamAwadhi** [comment]
Ready [JamaaSMPP](https://www.nuget.org/packages/JamaaSMPP/)
